### Notas de aula de Computação Quântica <br> Autor: Jonas Maziero

# Portas de rotação para qudits

Vamos começar escrevendo as matrizes de Gell-Mann generalizadas para qudits:
\begin{align}
& S_x^{j,k} = |j\rangle\langle k| + |k\rangle\langle j|,\ 1\le j< k\le d,\\ 
& S_y^{j,k} = -i|j\rangle\langle k| + i|k\rangle\langle j|,\ 1\le j< k\le d,\\
& S_z^{j} = \sum_{k=1}^{j+1}\sqrt{\frac{2}{j(j+1)}}(-j)^{\delta_{k,j+1}}|k\rangle\langle k|,\ j=1,\cdots,d-1. 
\end{align}

As matrizes de rotação são então definidas por
$$R_\alpha^{j,k}(\theta) = e^{-i\theta S_\alpha^{j,k}/2},$$
com $\alpha=x,y,z.$

## Matrizes de Gell-Mann

In [44]:
import numpy as np
import math

In [52]:
def Sx(j,k,d):
    # d = qudit dimension
    # j,k = identification of the Gell-Mann matrix
    # th = rotation angle
    j = j-1; k = k-1
    sx = np.zeros((d,d), dtype=complex)
    sx[j,k] = 1
    sx[k,j] = sx[j,k]
    return sx

def Sy(j,k,d):
    # d = qudit dimension
    # j,k = identification of the Gell-Mann matrix
    # th = rotation angle
    j = j-1; k = k-1
    sy = np.zeros((d,d), dtype=complex)
    sy[j,k] = -1j
    sy[k,j] = -sy[j,k]
    return sy

def Sz(j,d):
    # d = qudit dimension
    # j = identification of the Gell-Mann matrix
    # th = rotation angle
    sz = np.zeros((d,d), dtype=complex)
    for k in range(0,j+1):
        sz[k,k] = math.sqrt(2/(j*(j+1)))
        if k == j: # corrige para iniciar k em 0
            sz[k,k] = sz[k,k]*(-j)
    return sz

In [53]:
d = 2; j = 1; k = 2; Sx(j,k,d), Sy(j,k,d), Sz(j,d)

(array([[0.+0.j, 1.+0.j],
        [1.+0.j, 0.+0.j]]),
 array([[ 0.+0.j, -0.-1.j],
        [ 0.+1.j,  0.+0.j]]),
 array([[ 1.+0.j,  0.+0.j],
        [ 0.+0.j, -1.+0.j]]))

In [54]:
d = 3; Sx(1,2,d), Sx(1,3,d), Sx(2,3,d)

(array([[0.+0.j, 1.+0.j, 0.+0.j],
        [1.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j]]),
 array([[0.+0.j, 0.+0.j, 1.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j],
        [1.+0.j, 0.+0.j, 0.+0.j]]),
 array([[0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 1.+0.j],
        [0.+0.j, 1.+0.j, 0.+0.j]]))

In [55]:
d = 3; Sy(1,2,d), Sy(1,3,d), Sy(2,3,d)

(array([[ 0.+0.j, -0.-1.j,  0.+0.j],
        [ 0.+1.j,  0.+0.j,  0.+0.j],
        [ 0.+0.j,  0.+0.j,  0.+0.j]]),
 array([[ 0.+0.j,  0.+0.j, -0.-1.j],
        [ 0.+0.j,  0.+0.j,  0.+0.j],
        [ 0.+1.j,  0.+0.j,  0.+0.j]]),
 array([[ 0.+0.j,  0.+0.j,  0.+0.j],
        [ 0.+0.j,  0.+0.j, -0.-1.j],
        [ 0.+0.j,  0.+1.j,  0.+0.j]]))

In [56]:
d = 3; Sz(1,d), Sz(2,d)

(array([[ 1.+0.j,  0.+0.j,  0.+0.j],
        [ 0.+0.j, -1.+0.j,  0.+0.j],
        [ 0.+0.j,  0.+0.j,  0.+0.j]]),
 array([[ 0.57735027+0.j,  0.        +0.j,  0.        +0.j],
        [ 0.        +0.j,  0.57735027+0.j,  0.        +0.j],
        [ 0.        +0.j,  0.        +0.j, -1.15470054+0.j]]))

In [58]:
1/math.sqrt(3), -2/math.sqrt(3)

(0.5773502691896258, -1.1547005383792517)

## $d=2$
Nesse caso temos uma única possibilidade em cada "direção":
\begin{align}
& S_x^{1,2} = |1\rangle\langle 2| + |2\rangle\langle 1| = \begin{bmatrix}0&1\\1&0\end{bmatrix} = |+\rangle\langle +| - |-\rangle\langle -|, \\ 
& S_y^{1,2} = -i|1\rangle\langle 2| + i|2\rangle\langle 1| = \begin{bmatrix}0&-i\\i&0\end{bmatrix} = |\oplus\rangle\langle \oplus| - |\ominus\rangle\langle \ominus|, \\
& S_z^{1} = \sum_{k=1}^{1+1}\sqrt{\frac{2}{1(1+1)}}(-1)^{\delta_{k,1+1}}|k\rangle\langle k| = \sum_{k=1}^{2}\sqrt{1}(-1)^{\delta_{k,2}}|k\rangle\langle k| = |1\rangle\langle 1| - |2\rangle\langle 2| = \begin{bmatrix}1&0\\0&1\end{bmatrix}, 
\end{align}
em que
\begin{align}
& |\pm\rangle = (|1\rangle \pm |2\rangle)/\sqrt{2}, \\
& |\oplus\rangle = (|1\rangle + i |2\rangle)/\sqrt{2}, \\
& |\ominus\rangle = (|1\rangle - i |2\rangle)/\sqrt{2}.
\end{align}

As matrizes de rotação correspondentes são
\begin{align}
R_x^{1,2}(\theta) & = e^{-i\theta S_x^{1,2}/2} = e^{(-i\theta/2)(|+\rangle\langle +| - |-\rangle\langle -|)} \\ 
& = e^{-i\theta/2}|+\rangle\langle +| + e^{i\theta/2}|-\rangle\langle -| \\ 
& = e^{-i\theta/2}(|1\rangle\langle 1|+|1\rangle\langle 2|+|2\rangle\langle 1|+|2\rangle\langle 2|)/2 + e^{i\theta/2}(|1\rangle\langle 1|-|1\rangle\langle 2|-|2\rangle\langle 1|+|2\rangle\langle 2|)/2 \\
& = \frac{e^{-i\theta/2}+e^{i\theta/2}}{2}(|1\rangle\langle 1|+|2\rangle\langle 2|) + \frac{e^{-i\theta/2}-e^{i\theta/2}}{2}(|1\rangle\langle 2|+|2\rangle\langle 1|) \\
& = \cos(\theta/2)(|1\rangle\langle 1|+|2\rangle\langle 2|) -i\sin(\theta/2)(|1\rangle\langle 2|+|2\rangle\langle 1|) \\
& = \begin{bmatrix}\cos(\theta/2)&-i\sin(\theta/2)\\-i\sin(\theta/2)&\cos(\theta/2)\end{bmatrix},\\
R_y^{1,2}(\theta) & = e^{-i\theta S_y^{1,2}/2} = e^{(-i\theta/2)(|\oplus\rangle\langle \oplus| - |\ominus\rangle\langle \ominus|)} \\ 
& = e^{-i\theta/2}|\oplus\rangle\langle \oplus| + e^{i\theta/2}|\ominus\rangle\langle \ominus| \\ 
& = e^{-i\theta/2}(|1\rangle\langle 1|-i|1\rangle\langle 2|+i|2\rangle\langle 1|+|2\rangle\langle 2|)/2 + e^{i\theta/2}(|1\rangle\langle 1|+i|1\rangle\langle 2|-i|2\rangle\langle 1|+|2\rangle\langle 2|)/2 \\
& = \frac{e^{-i\theta/2}+e^{i\theta/2}}{2}(|1\rangle\langle 1|+|2\rangle\langle 2|) + \frac{e^{-i\theta/2}-e^{i\theta/2}}{2}(-i|1\rangle\langle 2|+i|2\rangle\langle 1|) \\
& = \cos(\theta/2)(|1\rangle\langle 1|+|2\rangle\langle 2|) -i\sin(\theta/2)(-i|1\rangle\langle 2|+i|2\rangle\langle 1|) \\
& = \begin{bmatrix}\cos(\theta/2)&-\sin(\theta/2)\\ \sin(\theta/2)&\cos(\theta/2)\end{bmatrix},\\
R_z^{1}(\theta) & = e^{-i\theta S_z^{1}/2} = e^{(-i\theta/2)(|1\rangle\langle 1| - |2\rangle\langle 2|)} \\ 
& = e^{-i\theta/2}|1\rangle\langle 1| + e^{i\theta/2}|2\rangle\langle 2| \\ 
& = \begin{bmatrix}e^{-i\theta/2}&0\\ 0&e^{i\theta/2}\end{bmatrix}.
\end{align}

## d=3

Nesse caso, vamos fazer só alguns exemplos para notar o padrão geral:
\begin{align}
& S_x^{1,2} = |1\rangle\langle 2| + |2\rangle\langle 1| = \begin{bmatrix}0&1&0\\1&0&0\\0&0&0\end{bmatrix} = |+\rangle\langle +| - |-\rangle\langle -| + (0)|3\rangle\langle 3|,  
\end{align}
em que
\begin{align}
|\pm\rangle = (|1\rangle \pm |2\rangle)/\sqrt{2}.
\end{align}

Teremos assim que
\begin{align}
R_x^{1,2}(\theta) & = e^{-i\theta S_x^{1,2}/2} = e^{(-i\theta/2)(|+\rangle\langle +| - |-\rangle\langle -| + (0)|3\rangle\langle 3|)} \\ 
& = e^{-i\theta/2}|+\rangle\langle +| + e^{i\theta/2}|-\rangle\langle -| + e^{0}|3\rangle\langle 3| \\ 
& = e^{-i\theta/2}(|1\rangle\langle 1|+|1\rangle\langle 2|+|2\rangle\langle 1|+|2\rangle\langle 2|)/2 + e^{i\theta/2}(|1\rangle\langle 1|-|1\rangle\langle 2|-|2\rangle\langle 1|+|2\rangle\langle 2|)/2  + |3\rangle\langle 3| \\
& = \frac{e^{-i\theta/2}+e^{i\theta/2}}{2}(|1\rangle\langle 1|+|2\rangle\langle 2|) + \frac{e^{-i\theta/2}-e^{i\theta/2}}{2}(|1\rangle\langle 2|+|2\rangle\langle 1|)  + |3\rangle\langle 3| \\
& = \cos(\theta/2)(|1\rangle\langle 1|+|2\rangle\langle 2|) -i\sin(\theta/2)(|1\rangle\langle 2|+|2\rangle\langle 1|)  + |3\rangle\langle 3| \\
& = \begin{bmatrix}\cos(\theta/2)&-i\sin(\theta/2) & 0 \\ -i\sin(\theta/2)&\cos(\theta/2)&0 \\ 0&0&1\end{bmatrix}.
\end{align}

## d=4

Nesse caso, temos
\begin{align}
& S_x^{1,2} = |1\rangle\langle 2| + |2\rangle\langle 1| = \begin{bmatrix}0&1&0&0\\1&0&0&0\\0&0&0&0\\0&0&0&0\end{bmatrix} = |+\rangle\langle +| - |-\rangle\langle -| + (0)|3\rangle\langle 3| + (0)|4\rangle\langle 4|,  
\end{align}
em que
\begin{align}
|\pm\rangle = (|1\rangle \pm |2\rangle)/\sqrt{2}.
\end{align}

Teremos assim que
\begin{align}
R_x^{1,2}(\theta) & = e^{-i\theta S_x^{1,2}/2} = e^{(-i\theta/2)(|+\rangle\langle +| - |-\rangle\langle -| + (0)|3\rangle\langle 3| + (0)|4\rangle\langle 4|)} \\ 
& = e^{-i\theta/2}|+\rangle\langle +| + e^{i\theta/2}|-\rangle\langle -| + e^{0}|3\rangle\langle 3| + e^{0}|4\rangle\langle 4| \\ 
& = e^{-i\theta/2}(|1\rangle\langle 1|+|1\rangle\langle 2|+|2\rangle\langle 1|+|2\rangle\langle 2|)/2 + e^{i\theta/2}(|1\rangle\langle 1|-|1\rangle\langle 2|-|2\rangle\langle 1|+|2\rangle\langle 2|)/2  + |3\rangle\langle 3| + |4\rangle\langle 4| \\
& = \frac{e^{-i\theta/2}+e^{i\theta/2}}{2}(|1\rangle\langle 1|+|2\rangle\langle 2|) + \frac{e^{-i\theta/2}-e^{i\theta/2}}{2}(|1\rangle\langle 2|+|2\rangle\langle 1|) + |3\rangle\langle 3| + |4\rangle\langle 4| \\
& = \cos(\theta/2)(|1\rangle\langle 1|+|2\rangle\langle 2|) -i\sin(\theta/2)(|1\rangle\langle 2|+|2\rangle\langle 1|) + |3\rangle\langle 3| + |4\rangle\langle 4| \\
& = \begin{bmatrix}\cos(\theta/2)&-i\sin(\theta/2) & 0 & 0 \\ -i\sin(\theta/2)&\cos(\theta/2)&0&0 \\ 0&0&1&0\\ 0&0&0&1\end{bmatrix}.
\end{align}

## Caso geral

Esse mesmo padrão vai se repetir para qualquer dimensão. Ou seja, a rotação bidimensional é aplicada no sub-espaço com índeces $j,k$ e a indentidade é aplicada no resto do espaço vetorial. 

Os elementos não nulos de $R_x^{j,k}$ são
\begin{align}
& \langle j|R_x^{j,k}(\theta)|j\rangle = \langle k|R_x^{j,k}(\theta)|k\rangle = \cos(\theta/2), \\ 
& \langle j|R_x^{j,k}(\theta)|k\rangle = \langle k|R_x^{j,k}(\theta)|j\rangle = -i\sin(\theta/2),\\
& \langle l|R_x^{j,k}(\theta)|l\rangle = 1;\ l\ne j\ \text{e}\ l\ne k.
\end{align}

Os elementos não nulos de $R_y^{j,k}$ são
\begin{align}
& \langle j|R_y^{j,k}(\theta)|j\rangle = \langle k|R_y^{j,k}(\theta)|k\rangle = \cos(\theta/2), \\ 
& \langle j|R_y^{j,k}(\theta)|k\rangle = -\langle k|R_y^{j,k}(\theta)|j\rangle = -\sin(\theta/2),\\
& \langle l|R_y^{j,k}(\theta)|l\rangle = 1;\ l\ne j\ \text{e}\ l\ne k.
\end{align}

Os elementos não nulos de $R_z^{j}$ são
\begin{align}
& \langle k|R_z^{j}(\theta)|k\rangle = \exp\Big(-i\frac{\theta}{2}\sqrt{\frac{2}{j(j+1)}}(-j)^{\delta_{k,j+1}}\Big);\ k=1,\cdots,j+1,\\
& \langle k|R_z^{j}(\theta)|k\rangle = 1;\ k=j,\cdots,d.
\end{align}

In [65]:
def Rx(j,k,d,th):
    # d = qudit dimension
    # j,k = identification of the Gell-Mann matrix
    # th = rotation angle
    j = j-1; k = k-1
    rx = np.eye(d, dtype=complex)
    rx[j,j] = math.cos(th/2)
    rx[k,k] = rx[j,j]
    rx[j,k] = -1j*math.sin(th/2)
    rx[k,j] = rx[j,k]
    return rx

def Ry(j,k,d,th):
    # d = qudit dimension
    # j,k = identification of the Gell-Mann matrix
    # th = rotation angle
    j = j-1; k = k-1
    ry = np.eye(d, dtype=complex)
    ry[j,j] = math.cos(th/2)
    ry[k,k] = ry[j,j]
    ry[j,k] = -math.sin(th/2)
    ry[k,j] = -ry[j,k]
    return ry

def Rz(j,d,th):
    # d = qudit dimension
    # j = identification of the Gell-Mann matrix
    # th = rotation angle
    rz = np.eye(d, dtype=complex)
    for k in range(0,j+1):
        angle = (th/2)*math.sqrt(2/(j*(j+1)))
        if k == j: # corrige para iniciar k em 0
            angle = angle*(-j)
        rz[k,k] = math.cos(angle) - 1j*math.sin(angle)
    return rz

In [66]:
d = 2; j = 1; k = 2; th = 0; Rx(j,k,d,th), Ry(j,k,d,th), Rz(j,d,th)

(array([[1.+0.j, 0.-0.j],
        [0.-0.j, 1.+0.j]]),
 array([[ 1.+0.j, -0.+0.j],
        [ 0.-0.j,  1.+0.j]]),
 array([[1.+0.j, 0.+0.j],
        [0.+0.j, 1.+0.j]]))

In [67]:
d = 3; j = 1; k = 2; th = 0; Rx(j,k,d,th), Ry(j,k,d,th), Rz(j,d,th)

(array([[1.+0.j, 0.-0.j, 0.+0.j],
        [0.-0.j, 1.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 1.+0.j]]),
 array([[ 1.+0.j, -0.+0.j,  0.+0.j],
        [ 0.-0.j,  1.+0.j,  0.+0.j],
        [ 0.+0.j,  0.+0.j,  1.+0.j]]),
 array([[1.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 1.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 1.+0.j]]))

## Referências

1. J. Maziero, “Computing Coherence Vectors and Correlation Matrices with Application to Quantum Discord Quantification,” Advances in Mathematical Physics, vol. 2016, p. e6892178, Jun. 2016, doi: 10.1155/2016/6892178.

