# Porta de rotação controlada

## Portas de rotação

Lembrando, as matrizes de Gell-Mann são
\begin{align}
& S_x^{jk} = |j\rangle\langle k| + |k\rangle\langle j|;\ 1\le j< k\le d, \\
& S_y^{jk} = -i|j\rangle\langle k| + i|k\rangle\langle j|;\ 1\le j< k\le d, \\
& S_z^j = \sqrt{\frac{2}{j(j+1)}}\Big(\sum_{k=1}^{j}|k\rangle\langle k|-j|j+1\rangle\langle j+1|\Big);\ j=1,\cdots,d-1.
\end{align}
Essas matrizes são hermitianas e, junto com a matriz identidade, formam uma base para $\mathbb{C}^{d\times d}.$

Rotações
$$R_\alpha^{jk}(\theta) = e^{-i\theta S_\alpha^{jk}/2}.$$

---
Digressão:

Temos que
\begin{align}
(S_x^{jk})^2 & = (|j\rangle\langle k| + |k\rangle\langle j|)(|j\rangle\langle k| + |k\rangle\langle j|) \\
& = |j\rangle\langle k|\delta_{kj} + |j\rangle\langle j| + |k\rangle\langle k| + |k\rangle\langle j|\delta_{jk} \\
& = |j\rangle\langle j| + |k\rangle\langle k| \\
& = I_{jk}, \\
(S_y^{jk})^2 & = (-i|j\rangle\langle k| + i|k\rangle\langle j|)(-i|j\rangle\langle k| + i|k\rangle\langle j|) \\
& = i^2|j\rangle\langle k|\delta_{kj} - i^2|j\rangle\langle j| - i^2|k\rangle\langle k| + i^2|k\rangle\langle j|\delta_{kj} \\
& = |j\rangle\langle j| + |k\rangle\langle k| \\
& = I_{jk}, \\
(S_z^j)^2 & = \sum_{k=1}^{j+1}\sqrt{\frac{2}{j(j+1)}}(-j)^{\delta_{k,j+1}}|k\rangle\langle k|\sum_{k'=1}^{j+1}\sqrt{\frac{2}{j(j+1)}}(-j)^{\delta_{k',j+1}}|k'\rangle\langle k|' \\
& = \sum_{k,k'=1}^{j+1}\frac{2}{j(j+1)}(-j)^{\delta_{k,j+1}}(-j)^{\delta_{k',j+1}}|k\rangle\langle k'|\delta_{k,k'} \\
& = \frac{2}{j(j+1)}\sum_{k=1}^{j+1}(-j)^{2\delta_{k,j+1}}|k\rangle\langle k| = \frac{2}{j(j+1)}\sum_{k=1}^{j+1}j|k\rangle\langle k| \\
& = \frac{2}{j+1}\sum_{k=1}^{j+1}|k\rangle\langle k|,
\end{align}
em que $I_{jk}$ é o subespaço gerado por $\{|j\rangle,|k\rangle\}.$

Para qualquer matriz $S$ tal que
$$S^2=I$$
temos que
\begin{align}
e^{-i\theta S} & = \sum_{j=0}^\infty \frac{(-i\theta S)^j}{j!} \\
& = \frac{(-i\theta S)^0}{0!} + \frac{(-i\theta S)^1}{1!} + \frac{(-i\theta S)^2}{2!} + \frac{(-i\theta S)^3}{3!} + \frac{(-i\theta S)^4}{4!} + \frac{(-i\theta S)^5}{5!} + \frac{(-i\theta S)^6}{6!} + \frac{(-i\theta S)^7}{7!} + \cdots \\
& = I -i\theta S - \frac{\theta^2 S^2}{2!} + i \frac{\theta^3 S^2 S}{3!} + \frac{\theta^4 S^2 S^2}{4!} -i \frac{\theta^5 S^2 S^2 S}{5!} - \frac{\theta^6 S^2 S^2 S^2}{6!} + i \frac{\theta^7 S^2 S^2 S^2 S}{7!} \cdots \\
& = \Big(1 - \frac{\theta^2}{2!} + \frac{\theta^4}{4!} - \frac{\theta^6}{6!} + \cdots \Big)I -i\Big(\theta - \frac{\theta^3}{3!} + \frac{\theta^5}{5!} - \frac{\theta^7}{7!} + \cdots\Big) \\
& = \cos(\theta)I -i\sin(\theta)S.
\end{align}

No entanto, para matrizes de Gell-Mann temos que
$$(S_\alpha^{jk})^2\ne I,$$
e a fórmula acima não pode ser aplicada. Na verdade
$$(S_\alpha^{jk})^2\ne I_{jk},$$
em que $I_{jk}$ é o operador identidade no subespaço gerado por $\{|j\rangle,|k\rangle\}.$

In [1]:
from sympy import series, symbols, cos, sin
th = symbols('theta')
series(cos(th),th,0,10)

1 - theta**2/2 + theta**4/24 - theta**6/720 + theta**8/40320 + O(theta**10)

In [2]:
series(sin(th),th,0,10)

theta - theta**3/6 + theta**5/120 - theta**7/5040 + theta**9/362880 + O(theta**10)

---

Então, para as matrizes de Gell-Mann definimos
\begin{align}
& |\pm\rangle_{jk} = (|j\rangle\pm|k\rangle)/\sqrt{2}, \\
& |\oplus\rangle_{jk} = (|j\rangle+i|k\rangle)/\sqrt{2}, \\
& |\ominus\rangle_{jk} = (|j\rangle-i|k\rangle)/\sqrt{2}.
\end{align}
Teremos assim que
\begin{align}
S_x^{jk}|\pm\rangle_{jk} & = (|j\rangle\langle k|+|k\rangle\langle j|)(|j\rangle\pm|k\rangle)/\sqrt{2} \\
& = (|k\rangle\pm|j\rangle)/\sqrt{2} \\
& = (\pm 1)(|j\rangle\pm|k\rangle)/\sqrt{2} \\
& = (\pm 1)|\pm\rangle_{jk}, \\
S_y^{jk}|\oplus\rangle_{jk} & = (-i|j\rangle\langle k|+i|k\rangle\langle j|)(|j\rangle+i|k\rangle)/\sqrt{2} \\
& = (i|k\rangle+|j\rangle)/\sqrt{2} \\
& = (+ 1)|\oplus\rangle_{jk}, \\
S_y^{jk}|\ominus\rangle_{jk} & = (-i|j\rangle\langle k|+i|k\rangle\langle j|)(|j\rangle-i|k\rangle)/\sqrt{2} \\
& = (i|k\rangle-|j\rangle)/\sqrt{2} \\
& = (-1)(-i|k\rangle+|j\rangle)/\sqrt{2} \\
& = (-1)|\ominus\rangle_{jk}.
\end{align}

Por conseguinte, podemos escrever as decomposições espectrais
\begin{align}
& S_x^{jk} = |+\rangle\langle +|_{jk} - |-\rangle\langle -|_{jk} + \sum_{l(l\ne j,l\ne k)}(0)|l\rangle\langle l|, \\
& S_y^{jk} = |\oplus\rangle\langle \oplus|_{jk} - |\ominus\rangle\langle \ominus|_{jk} + \sum_{l(l\ne j,l\ne k)}(0)|l\rangle\langle l|,
\end{align}
e as matrizes de rotação ficam dadas por
\begin{align}
R_x^{jk}(\theta) & = e^{-i\theta S_x^{jk}/2} \\
& = e^{-i\theta/2}|+\rangle\langle +| + e^{i\theta/2}|-\rangle\langle - | + \sum_{l(l\ne j,l\ne k)}e^{-i\theta(0)/2}|l\rangle\langle l|, \\
& = e^{-i\theta/2}\frac{1}{2}(|j\rangle\langle j|+|j\rangle\langle k|+|k\rangle\langle j|+|k\rangle\langle k|) + e^{i\theta/2}\frac{1}{2}(|j\rangle\langle j|-|j\rangle\langle k|-|k\rangle\langle j|+|k\rangle\langle k|) + \sum_{l(l\ne j,l\ne k)}(1)|l\rangle\langle l|, \\
& = \cos(\theta/2)(|j\rangle\langle j|+|k\rangle\langle k|) - i\sin(\theta/2)(|j\rangle\langle k|+|k\rangle\langle j|) + \sum_{l(l\ne j,l\ne k)}|l\rangle\langle l|, \\
R_y^{jk}(\theta) & = e^{-i\theta S_y^{jk}/2} \\
& = e^{-i\theta/2}|\oplus\rangle\langle \oplus| + e^{i\theta/2}|\ominus\rangle\langle \ominus| + \sum_{l(l\ne j,l\ne k)}e^{-i\theta(0)/2}|l\rangle\langle l|, \\
& = e^{-i\theta/2}\frac{1}{2}(|j\rangle\langle j|-i|j\rangle\langle k|+i|k\rangle\langle j|+|k\rangle\langle k|) + e^{i\theta/2}\frac{1}{2}(|j\rangle\langle j|+i|j\rangle\langle k|-i|k\rangle\langle j|+|k\rangle\langle k|) + \sum_{l(l\ne j,l\ne k)}(1)|l\rangle\langle l|, \\
& = \cos(\theta/2)(|j\rangle\langle j|+|k\rangle\langle k|) - \sin(\theta/2)(|j\rangle\langle k|-|k\rangle\langle j|) + \sum_{l(l\ne j,l\ne k)}|l\rangle\langle l|.
\end{align}

Os elementos de matriz das matrizes de rotação são dados por
\begin{align}
\langle m|R_x^{jk}(\theta)|n\rangle & = \cos(\theta/2)(\langle m|j\rangle\langle j|n\rangle+\langle m|k\rangle\langle k|n\rangle) - i\sin(\theta/2)(\langle m|j\rangle\langle k|n\rangle+\langle m|k\rangle\langle j|n\rangle) + \sum_{l(l\ne j,l\ne k)}\langle m|l\rangle\langle l|n\rangle \\
& = \cos(\theta/2)(\delta_{mj}\delta_{jn}+\delta_{mk}\delta_{kn}) - i\sin(\theta/2)(\delta_{mj}\delta_{kn}+\delta_{mk}\delta_{jn}) + \sum_{l(l\ne j,l\ne k)}\delta_{ml}\delta_{ln}, \\
\langle m|R_y^{jk}(\theta)|n\rangle & = \cos(\theta/2)(\langle m|j\rangle\langle j|n\rangle+\langle m|k\rangle\langle k|n\rangle) - \sin(\theta/2)(\langle m|j\rangle\langle k|n\rangle-\langle m|k\rangle\langle j|n\rangle) + \sum_{l(l\ne j,l\ne k)}\langle m|l\rangle\langle l|n\rangle \\
& = \cos(\theta/2)(\delta_{mj}\delta_{jn}+\delta_{mk}\delta_{kn}) - \sin(\theta/2)(\delta_{mj}\delta_{kn}-\delta_{mk}\delta_{jn}) + \sum_{l(l\ne j,l\ne k)}\delta_{ml}\delta_{ln}.
\end{align}

Vemos assim que os elementos não nulos de $R_x^{jk}$ são
\begin{align}
& \langle j|R_x^{jk}(\theta)|j\rangle = \langle k|R_x^{jk}(\theta)|k\rangle = \cos(\theta/2), \\ 
& \langle j|R_x^{jk}(\theta)|k\rangle = \langle k|R_x^{jk}(\theta)|j\rangle = -i\sin(\theta/2),\\
& \langle l|R_x^{jk}(\theta)|l\rangle = 1;\ l\ne j\ \text{e}\ l\ne k.
\end{align}
Os elementos não nulos de $R_y^{jk}$ são
\begin{align}
& \langle j|R_y^{jk}(\theta)|j\rangle = \langle k|R_y^{jk}(\theta)|k\rangle = \cos(\theta/2), \\ 
& \langle j|R_y^{jk}(\theta)|k\rangle = -\langle k|R_y^{jk}(\theta)|j\rangle = -\sin(\theta/2),\\
& \langle l|R_y^{jk}(\theta)|l\rangle = 1;\ l\ne j\ \text{e}\ l\ne k.
\end{align}

In [3]:
from sympy import symbols, sin, cos, eye, sqrt, simplify
th = symbols('theta')

def f_Rx(j,k,d,th):
    # d = qudit dimension
    # j,k = identification of the Gell-Mann x-type matrix
    # th = rotation angle
    j = j-1; k = k-1
    rx = eye(d)
    rx[j,j] = cos(th/2); rx[k,k] = rx[j,j]
    rx[j,k] = -1j*sin(th/2); rx[k,j] = rx[j,k]
    return rx

def f_Ry(j,k,d,th):
    # d = qudit dimension
    # j,k = identification of the Gell-Mann y-type matrix
    # th = rotation angle
    j = j-1; k = k-1
    ry = eye(d)
    ry[j,j] = cos(th/2); ry[k,k] = ry[j,j]
    ry[j,k] = -sin(th/2); ry[k,j] = -ry[j,k]
    return ry

In [4]:
j=1;k=2;d=2; Rx = f_Rx(j,k,d,th); Rx

Matrix([
[       cos(theta/2), -1.0*I*sin(theta/2)],
[-1.0*I*sin(theta/2),        cos(theta/2)]])

In [6]:
j=1;k=2;d=3; Rx = f_Rx(j,k,d,th); Rx

Matrix([
[       cos(theta/2), -1.0*I*sin(theta/2), 0],
[-1.0*I*sin(theta/2),        cos(theta/2), 0],
[                  0,                   0, 1]])

In [5]:
j=1;k=2;d=2; Ry = f_Ry(1,2,d,th); Ry

Matrix([
[cos(theta/2), -sin(theta/2)],
[sin(theta/2),  cos(theta/2)]])

In [9]:
j=1;k=2;d=3; Ry = f_Ry(1,2,d,th); Ry

Matrix([
[cos(theta/2), -sin(theta/2), 0],
[sin(theta/2),  cos(theta/2), 0],
[           0,             0, 1]])

Já para as matrizes de Gell da família $z$ escrevemos a decomposição espectral
$$S_z^j = \sqrt{\frac{2}{j(j+1)}}\Big(\sum_{k=1}^{j}|k\rangle\langle k|-j|j+1\rangle\langle j+1|\Big) + \sum_{k=j+2}^d (0)|k\rangle\langle k|$$
com $j=1,\cdots,d-1.$

Assim a matriz de rotação fica escrita como
\begin{align}
R_z^j(\theta) & = e^{-i\theta S_x^{jk}/2} \\
& = \sum_{k=1}^{j}\exp\Big(-i\sqrt{\frac{2}{j(j+1)}}\theta/2\Big)|k\rangle\langle k| + \exp\Big(i\sqrt{\frac{2}{j(j+1)}}j\theta/2\Big)|j+1\rangle\langle j+1| + \sum_{k=j+2}^d e^0|k\rangle\langle k| \\
& = \sum_{k=1}^{j}\exp\Big(-i\sqrt{\frac{2}{j(j+1)}}\theta/2\Big)|k\rangle\langle k| + \exp\Big(i\sqrt{\frac{2}{j(j+1)}}j\theta/2\Big)|j+1\rangle\langle j+1| + \sum_{k=j+2}^d |k\rangle\langle k|.
\end{align}

Os elementos não nulos de $R_z^{j}$ são
\begin{align}
& \langle k|R_z^{j}(\theta)|k\rangle = \exp\Big(-i\frac{\theta}{2}\sqrt{\frac{2}{j(j+1)}}\Big);\ k=1,\cdots,j,\\
& \langle k|R_z^{j}(\theta)|k\rangle = \exp\Big(i\frac{j\theta}{2}\sqrt{\frac{2}{j(j+1)}}\Big);\ k=j+1,\\
& \langle k|R_z^{j}(\theta)|k\rangle = 1;\ k=j+2,\cdots,d.
\end{align}

In [66]:
def f_Rz(j,d,th):
    # d = qudit dimension
    # j = identification of the Gell-Mann matrix
    # th = rotation angle
    rz = eye(d)
    angle = (th/2)*sqrt(2/(j*(j+1)))
    for k in range(0,j):
        rz[k,k] = cos(angle) - 1j*sin(angle)
    angle = j*angle
    rz[j,j] = cos(angle) + 1j*sin(angle)
    if j < d-1:
        for k in range(j+1,d):
            rz[k,k] = 1
    return rz

In [67]:
th = symbols('theta')
j=1; d=2; Rz = simplify(f_Rz(j,d,th)); Rz

Matrix([
[1.0*exp(-0.5*I*theta),                    0],
[                    0, 1.0*exp(0.5*I*theta)]])

In [68]:
from sympy import pi; th = pi
j=1; d=2; Rz = simplify(f_Rz(j,d,th)); Rz

Matrix([
[-1.0*I,     0],
[     0, 1.0*I]])

In [52]:
th = symbols('theta')
j=1; d=3; Rz = simplify(f_Rz(j,d,th)); Rz

Matrix([
[1,                    0, 0],
[0, 1.0*exp(0.5*I*theta), 0],
[0,                    0, 1]])

In [20]:
# transform from sympy Matrix to numpy array
from sympy import Matrix, matrix2numpy, pi
#Msp = Matrix([[1,2],[3,4]])
j=1; k=2; d=2; Rx = f_Rx(j,k,d,pi); Msp = Rx
Mnp = matrix2numpy(Msp, dtype=complex)
Msp,Mnp

(Matrix([
 [     0, -1.0*I],
 [-1.0*I,      0]]),
 array([[0.+0.j, 0.-1.j],
        [0.-1.j, 0.+0.j]]))

## Porta de rotação controlada
$$C_{R_\alpha^{jk}(\theta)}^{c\rightarrow t} = \sum_{l=0}^{d-1}|l\rangle\langle l|\otimes R_\alpha^{jk}(l\theta) = \sum_{l=0}^{D-1}|l\rangle\langle l|\otimes e^{-il\theta S_\alpha^{jk}/2}.$$

Elementos de matriz da rotação controlada
\begin{align}
\langle m n|C_{R_\alpha^{jk}(\theta)}^{c\rightarrow t}|pq\rangle & = \sum_{l=0}^{d-1}\langle m|l\rangle\langle l|p\rangle\otimes \langle n|R_\alpha^{jk}(l\theta)|q\rangle \\ 
& = \sum_{l=0}^{d-1}\delta_{m,l}\delta_{l,p}\otimes \langle n|R_\alpha^{jk}(l\theta)|q\rangle \\
& = \delta_{m,p}\langle n|R_\alpha^{jk}(p\theta)|q\rangle.
\end{align}

Os elementos não nulos de $C_{R_x^{jk}(\theta)}^{c\rightarrow t}$ são
\begin{align}
& \langle pj|C_{R_x^{jk}(\theta)}^{c\rightarrow t}|pj\rangle = \langle pk|C_{R_x^{jk}(\theta)}^{c\rightarrow t}|pk\rangle = \cos(p\theta/2), \\ 
& \langle pj|C_{R_x^{jk}(\theta)}^{c\rightarrow t}|pk\rangle = \langle pk|C_{R_x^{jk}(\theta)}^{c\rightarrow t}|pj\rangle = -i\sin(p\theta/2),\\
& \langle pl|C_{R_x^{jk}(\theta)}^{c\rightarrow t}|pl\rangle = 1;\ l\ne j\ \text{e}\ l\ne k;\ p=1,\cdots,d.
\end{align}
Os elementos não nulos de $C_{R_y^{jk}(\theta)}^{c\rightarrow t}$ são
\begin{align}
& \langle pj|C_{R_y^{jk}(\theta)}^{c\rightarrow t}|pj\rangle = \langle pk|C_{R_y^{jk}(\theta)}^{c\rightarrow t}|pk\rangle = \cos(p\theta/2), \\ 
& \langle pj|C_{R_y^{jk}(\theta)}^{c\rightarrow t}|pk\rangle = -\langle pk|C_{R_y^{jk}(\theta)}^{c\rightarrow t}|pj\rangle = -\sin(p\theta/2),\\
& \langle pl|C_{R_y^{jk}(\theta)}^{c\rightarrow t}|pl\rangle = 1;\ l\ne j\ \text{e}\ l\ne k;\ p=1,\cdots,d.
\end{align}
Já os elementos não nulos de $C_{R_z^j(\theta)}^{c\rightarrow t}$ são
\begin{align}
& \langle pk|C_{R_z^j(\theta)}^{c\rightarrow t}|pk\rangle = \exp\Big(-i\frac{p\theta}{2}\sqrt{\frac{2}{j(j+1)}}\Big);\ k=1,\cdots,j,\\
& \langle pk|C_{R_z^j(\theta)}^{c\rightarrow t}|pk\rangle = \exp\Big(i\frac{jp\theta}{2}\sqrt{\frac{2}{j(j+1)}}\Big);\ k=j+1,\\
& \langle pk|C_{R_z^j(\theta)}^{c\rightarrow t}|pk\rangle = 1;\ k=j+2,\cdots,d.
\end{align}

Abaixo faço a programação em Sympy e em Numpy para comparação. No caso do Sympy é programado a simples soma das matrizes.

In [69]:
# Numpy

import numpy as np
import math

def f_CRx(j,k,d,th):
    # d = qudit dimension
    # j,k = identification of the Gell-Mann matrix
    # th = rotation angle
    crx = np.eye(d*d, dtype=complex)
    j = j-1; k = k-1
    for p in range(0,d):
        angle = (p*th)/2
        jl = p*d+j; kl = p*d+k 
        crx[jl,jl] = math.cos(angle); crx[kl,kl] = crx[jl,jl]
        crx[jl,kl] = -1j*math.sin(angle); crx[kl,jl] = crx[jl,kl]
    return crx

def f_CRy(j,k,d,th):
    # d = qudit dimension
    # j,k = identification of the Gell-Mann matrix
    # th = rotation angle
    j = j-1; k = k-1
    cry = np.eye(d*d, dtype=complex)
    for p in range(0,d):
        angle = (p*th)/2
        jl = p*d+j; kl = p*d+k
        cry[jl,jl] = math.cos(angle); cry[kl,kl] = cry[jl,jl]
        cry[jl,kl] = -math.sin(angle); cry[kl,jl] = -cry[jl,kl]
    return cry

def f_CRz(j,d,th):
    # d = qudit dimension
    # j = identification of the Gell-Mann matrix
    # th = rotation angle
    crz = np.eye(d*d, dtype=complex)
    for p in range(0,d):
        angle = ((p*th)/2)*math.sqrt(2/(j*(j+1)))
        for k in range(0,j):
            kl = p*d+k
            crz[kl,kl] = math.cos(angle) - 1j*math.sin(angle)
        angle = angle*j
        jl = p*d+j
        crz[jl,jl] = math.cos(angle) + 1j*math.sin(angle)
        if j < d:
            for k in range(j+1,d):
                kl = p*d+k
                rz[kl,kl] = 1
    return crz

In [14]:
# Sympy

from sympy.physics.quantum import TensorProduct
from sympy import zeros

def tp(A,B):
    return TensorProduct(A,B)

def ket(d,j):
    ke = zeros(d,1)
    ke[j] = 1
    return ke

ke = ket(2,0); ke*ke.T

Matrix([
[1, 0],
[0, 0]])

Para a implementação em Sympy:
$$C_{R_x^{jk}(\theta)}^{c\rightarrow t} = I_{\overline{c}}\otimes I_{\overline{t}}\otimes\sum_{l=0}^{d-1}|l\rangle\langle l|_c \otimes R_x^{jk}(l\theta)_t.$$

In [27]:
def ctrl_R(al,j,k,d,th,c,t):
    D = d*d
    CR = zeros(D,D)
    for l in range(0,d):
        ke = ket(d,l)
        if al == 'x':
            if c == 0 and t == 1:
                CR = CR + tp((ke*ke.T),f_Rx(j,k,d,l*th))
            elif c == 1 and t == 0:
                CR = CR + tp(f_Rx(j,k,d,l*th),(ke*ke.T))
        elif al == 'y':
            if c == 0 and t == 1:
                CR = CR + tp((ke*ke.T),f_Ry(j,k,d,l*th))
            elif c == 1 and t == 0:
                CR = CR + tp(f_Ry(j,k,d,l*th),(ke*ke.T))
        elif al == 'z':
            if c == 0 and t == 1:
                CR = CR + tp((ke*ke.T),f_Rz(j,d,l*th))
            elif c == 1 and t == 0:
                CR = CR + tp(f_Rz(j,d,l*th),(ke*ke.T))
    return CR

In [28]:
al='x'; j=1; k=2; d=2; c=0; t=1; th = symbols('theta'); ctrl_R(al,j,k,d,th,c,t)

Matrix([
[1, 0,                   0,                   0],
[0, 1,                   0,                   0],
[0, 0,        cos(theta/2), -1.0*I*sin(theta/2)],
[0, 0, -1.0*I*sin(theta/2),        cos(theta/2)]])

In [30]:
al='y'; j=1; k=2; d=2; c=1; t=0; th = symbols('theta'); ctrl_R(al,j,k,d,th,c,t)

Matrix([
[1,            0, 0,             0],
[0, cos(theta/2), 0, -sin(theta/2)],
[0,            0, 1,             0],
[0, sin(theta/2), 0,  cos(theta/2)]])

In [33]:
al='z'; j=1; k=j; d=2; c=1; t=0; th = symbols('theta'); simplify(ctrl_R(al,j,k,d,th,c,t))

Matrix([
[1, 0, 0,                    0],
[0, 1, 0,                    0],
[0, 0, 1,                    0],
[0, 0, 0, 1.0*exp(0.5*I*theta)]])

In [70]:
from sympy import pi
al='x'; j=1; k=2; d=2; c=0; t=1; th = pi; ctrl_R(al,j,k,d,th,c,t)

Matrix([
[1, 0,      0,      0],
[0, 1,      0,      0],
[0, 0,      0, -1.0*I],
[0, 0, -1.0*I,      0]])

In [71]:
j=1; k=2; d=2; th = math.pi; crx = f_CRx(j,k,d,th); crx # ok!

array([[1.000000e+00+0.j, 0.000000e+00-0.j, 0.000000e+00+0.j,
        0.000000e+00+0.j],
       [0.000000e+00-0.j, 1.000000e+00+0.j, 0.000000e+00+0.j,
        0.000000e+00+0.j],
       [0.000000e+00+0.j, 0.000000e+00+0.j, 6.123234e-17+0.j,
        0.000000e+00-1.j],
       [0.000000e+00+0.j, 0.000000e+00+0.j, 0.000000e+00-1.j,
        6.123234e-17+0.j]])

In [72]:
al='y'; j=1; k=2; d=2; c=0; t=1; th = pi; ctrl_R(al,j,k,d,th,c,t)

Matrix([
[1, 0, 0,  0],
[0, 1, 0,  0],
[0, 0, 0, -1],
[0, 0, 1,  0]])

In [73]:
j=1; k=2; d=2; th = math.pi; cry = f_CRy(j,k,d,th); cry # ok!

array([[ 1.000000e+00+0.j, -0.000000e+00+0.j,  0.000000e+00+0.j,
         0.000000e+00+0.j],
       [ 0.000000e+00-0.j,  1.000000e+00+0.j,  0.000000e+00+0.j,
         0.000000e+00+0.j],
       [ 0.000000e+00+0.j,  0.000000e+00+0.j,  6.123234e-17+0.j,
        -1.000000e+00+0.j],
       [ 0.000000e+00+0.j,  0.000000e+00+0.j,  1.000000e+00-0.j,
         6.123234e-17+0.j]])

In [76]:
al='z'; j=1; k=j; d=2; c=0; t=1; th = pi; simplify(ctrl_R(al,j,k,d,th,c,t))

Matrix([
[1, 0,      0,     0],
[0, 1,      0,     0],
[0, 0, -1.0*I,     0],
[0, 0,      0, 1.0*I]])

In [77]:
j=1; d=2; th = math.pi; crz = f_CRz(j,d,th); crz # ok!

array([[1.000000e+00+0.j, 0.000000e+00+0.j, 0.000000e+00+0.j,
        0.000000e+00+0.j],
       [0.000000e+00+0.j, 1.000000e+00+0.j, 0.000000e+00+0.j,
        0.000000e+00+0.j],
       [0.000000e+00+0.j, 0.000000e+00+0.j, 6.123234e-17-1.j,
        0.000000e+00+0.j],
       [0.000000e+00+0.j, 0.000000e+00+0.j, 0.000000e+00+0.j,
        6.123234e-17+1.j]])

## Caso geral

### Elementos não nulos de $C_{R_x^{jk}(\theta)}^{c\rightarrow t}$

Depois de algumas contas, notamos o seguinte. Se 
$$c<t$$
os elementos não nulos da rotação controlada são
\begin{align}
& \langle\cdots,k_{c-1},k_c,k_{c+1},\cdots,k_{t-1},j,k_{t+1},\cdots|C_{R_x^{jk}(\theta)}^{c\rightarrow t}|\cdots,k_{c-1},k_c,k_{c+1},\cdots,k_{t-1},j,k_{t+1},\cdots\rangle=\cos(k_c \theta/2), \\
& \langle\cdots,k_{c-1},k_c,k_{c+1},\cdots,k_{t-1},k,k_{t+1},\cdots|C_{R_x^{jk}(\theta)}^{c\rightarrow t}|\cdots,k_{c-1},k_c,k_{c+1},\cdots,k_{t-1},k,k_{t+1},\cdots\rangle=\cos(k_c \theta/2), \\
& \langle\cdots,k_{c-1},k_c,k_{c+1},\cdots,k_{t-1},j,k_{t+1},\cdots|C_{R_x^{jk}(\theta)}^{c\rightarrow t}|\cdots,k_{c-1},k_c,k_{c+1},\cdots,k_{t-1},k,k_{t+1},\cdots\rangle = -i\sin(k_c \theta/2), \\
& \langle\cdots,k_{c-1},k_c,k_{c+1},\cdots,k_{t-1},k,k_{t+1},\cdots|C_{R_x^{jk}(\theta)}^{c\rightarrow t}|\cdots,k_{c-1},k_c,k_{c+1},\cdots,k_{t-1},j,k_{t+1},\cdots\rangle = -i\sin(k_c \theta/2), \\
& \langle\cdots,k_{c-1},k_c,k_{c+1},\cdots,k_{t-1},l,k_{t+1},\cdots|C_{R_x^{jk}(\theta)}^{c\rightarrow t}|\cdots,k_{c-1},k_c,k_{c+1},\cdots,k_{t-1},l,k_{t+1},\cdots\rangle = 1, \\
\end{align}
pra $l\ne j;\ l\ne k;\ k_s = 0,\cdots,d-1;\ s=1,\cdots,N.$
Se 
$$c>t$$
os elementos não nulos da rotação controlada são
\begin{align}
& \langle\cdots,k_{t-1},j,k_{t+1},\cdots,k_{c-1},k_c,k_{c+1},\cdots|C_{R_x^{jk}(\theta)}^{c\rightarrow t}|\cdots,k_{t-1},j,k_{t+1},\cdots,k_{c-1},k_c,k_{c+1},\cdots\rangle=\cos(k_c \theta/2), \\
& \langle\cdots,k_{t-1},k,k_{t+1},\cdots,k_{c-1},k_c,k_{c+1},\cdots|C_{R_x^{jk}(\theta)}^{c\rightarrow t}|\cdots,k_{t-1},k,k_{t+1},\cdots,k_{c-1},k_c,k_{c+1},\cdots\rangle=\cos(k_c \theta/2), \\
& \langle\cdots,k_{t-1},j,k_{t+1},\cdots,k_{c-1},k_c,k_{c+1},\cdots|C_{R_x^{jk}(\theta)}^{c\rightarrow t}|\cdots,k_{t-1},k,k_{t+1},\cdots,k_{c-1},k_c,k_{c+1},\cdots\rangle = -i\sin(k_c \theta/2), \\
& \langle\cdots,k_{t-1},k,k_{t+1},\cdots,k_{c-1},k_c,k_{c+1},\cdots|C_{R_x^{jk}(\theta)}^{c\rightarrow t}|\cdots,k_{t-1},j,k_{t+1},\cdots,k_{c-1},k_c,k_{c+1},\cdots\rangle = -i\sin(k_c \theta/2), \\
& \langle\cdots,k_{t-1},l,k_{t+1},\cdots,k_{c-1},k_c,k_{c+1},\cdots|C_{R_x^{jk}(\theta)}^{c\rightarrow t}|\cdots,k_{t-1},l,k_{t+1},\cdots,k_{c-1},k_c,k_{c+1},\cdots\rangle = 1,
\end{align}
pra $l\ne j;\ l\ne k;\ k_s = 0,\cdots,d-1;\ s=1,\cdots,N.$

No final, os dois casos puderam ser implementados diretamente usando uma única função, sem necessidade de usar condicionais.

In [121]:
# Numpy

import numpy as np

def ctrl_Rx_qudits(d,N,t,c,j,k,th): # return the controlled-rotation gate
    # d = qudit dimension; N = No. of qudits; t = target qudit (0,...,N-1); c = control qudit (0,...,N-1)
    # j,k are the Gell-Mann matrix indeces; th is the rotation angle
    D = d**N
    CR = np.zeros((D,D), dtype=complex) # set all d^2N elements to 0
    Dl = D//d # dimension for N-1 qudits
    for m in range (0,Dl): # run over all states of N-1 qdits
        local = dec2den(m,N-1,d) # values for the local basis of N-1 qudits
        if N == 2: # to avoid issues in this case
            angle = (local[0]*th)/2
        else:
            angle = (local[c]*th)/2
        listj = local.copy(); listj.insert(t,j-1); intj = den2dec(listj,d) # integer for the j state
        listk = local.copy(); listk.insert(t,k-1); intk = den2dec(listk,d) # integer for the k state        
        CR[intj,intj] = math.cos(angle); CR[intk,intk] = CR[intj,intj]
        CR[intj,intk] = -1j*math.sin(angle); CR[intk,intj] = CR[intj,intk]
        for l in range(0,d):
            if l != j-1 and l != k-1:
                listl = local.copy(); listl.insert(t,l); intl = den2dec(listl,d) # integer for the l state
                CR[intl,intl] = 1
    return CR   

In [123]:
# tests for the tensor product of several matrices. One cannot start from a scalar. 
# The dimension is updated automatically.
s1 = Matrix([[0,1],[1,0]]); I2 = eye(2)
#M = 1; M = tp(M,s1); M = tp(M,I2); M # did not work
M = s1; M = tp(M,s1); M = tp(M,I2); M

Matrix([
[0, 0, 0, 0, 0, 0, 1, 0],
[0, 0, 0, 0, 0, 0, 0, 1],
[0, 0, 0, 0, 1, 0, 0, 0],
[0, 0, 0, 0, 0, 1, 0, 0],
[0, 0, 1, 0, 0, 0, 0, 0],
[0, 0, 0, 1, 0, 0, 0, 0],
[1, 0, 0, 0, 0, 0, 0, 0],
[0, 1, 0, 0, 0, 0, 0, 0]])

Para a implementação em Sympy:
$$C_{R_y^{jk}(\theta)}^{c\rightarrow t} = I_{\overline{c}}\otimes I_{\overline{t}}\otimes\sum_{l=0}^{d-1}|l\rangle\langle l|_c \otimes R_y^{jk}(l\theta)_t.$$

In [124]:
# Sympy

# general controlled rotation in sympy (seems ok)
def CRx_qudits_sympy(d,N,t,c,j,k,th):
    D = d**N
    CR = zeros(D,D)
    Id = eye(d)
    for m in range(0,d):
        ke = ket(d,m)
        s = 0
        if s == c:
            CRl = ke*ke.T
        elif s == t:
            CRl = f_Rx(j,k,d,m*th)
        else:
            CRl = Id
        for s in range(1,N):
            if s == c:
                CRl = tp(CRl,(ke*ke.T))
            elif s == t:
                CRl = tp(CRl,f_Rx(j,k,d,m*th))
            else:
                CRl = tp(CRl,Id)
        CR = CR + CRl
    return CR

In [125]:
j=1; k=2; d=2; N=3; th=symbols('theta'); c=1; t=2; crx = CRx_qudits_sympy(d,N,t,c,j,k,th); crx

Matrix([
[1, 0,                   0,                   0, 0, 0,                   0,                   0],
[0, 1,                   0,                   0, 0, 0,                   0,                   0],
[0, 0,        cos(theta/2), -1.0*I*sin(theta/2), 0, 0,                   0,                   0],
[0, 0, -1.0*I*sin(theta/2),        cos(theta/2), 0, 0,                   0,                   0],
[0, 0,                   0,                   0, 1, 0,                   0,                   0],
[0, 0,                   0,                   0, 0, 1,                   0,                   0],
[0, 0,                   0,                   0, 0, 0,        cos(theta/2), -1.0*I*sin(theta/2)],
[0, 0,                   0,                   0, 0, 0, -1.0*I*sin(theta/2),        cos(theta/2)]])

In [126]:
def dec2den(j,N,d): # converte de decimal para representação denária
    # j = valor decimal; 
    den = [0 for k in range(0,N)]
    jv = j
    for k in range(0,N):
        if jv >= d**(N-1-k):
            den[k] = jv//(d**(N-1-k))
            jv = jv - den[k]*d**(N-1-k)
    return den

dec2den(832,3,5)

[33, 1, 2]

In [127]:
def den2dec(local,d): # converte da representação denária pra a decimal
    # local = list with the local computational base state values 
    # d = individual qudit dimension
    N = len(local)
    j = 0
    for k in range(0,N):
        j += local[k]*d**(N-1-k)
    return j # value of the global computational basis index

den2dec([33,1,2],5)

832

In [128]:
# inserindo elementos em listas no numpy
l1 = [1, 2, 3, 5, 6]; print('l1=',l1)
l2 = l1.copy()
l2.insert(3,4) # 1º nº é a posição e o 2º nº é o valor a ser inserido
print('l2=',l2)

l1= [1, 2, 3, 5, 6]
l2= [1, 2, 3, 4, 5, 6]


In [129]:
import math
j=1; k=2; d=2; N=2; th=math.pi; t=1; c=0; crx = ctrl_Rx_qudits(d,N,t,c,j,k,th); crx # ok!

array([[1.000000e+00+0.j, 0.000000e+00-0.j, 0.000000e+00+0.j,
        0.000000e+00+0.j],
       [0.000000e+00-0.j, 1.000000e+00+0.j, 0.000000e+00+0.j,
        0.000000e+00+0.j],
       [0.000000e+00+0.j, 0.000000e+00+0.j, 6.123234e-17+0.j,
        0.000000e+00-1.j],
       [0.000000e+00+0.j, 0.000000e+00+0.j, 0.000000e+00-1.j,
        6.123234e-17+0.j]])

In [130]:
al='x';j=1;k=2;d=2; th=pi; c=0; t=1; crx = ctrl_R(al,j,k,d,th,c,t); Mnp = matrix2numpy(crx, dtype=complex); Mnp # sympy

array([[1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.-1.j],
       [0.+0.j, 0.+0.j, 0.-1.j, 0.+0.j]])

In [131]:
j=1; k=2; d=2; N=2; th=math.pi; t=0; c=1; crx = ctrl_Rx_qudits(d,N,t,c,j,k,th); crx # ok!

array([[1.000000e+00+0.j, 0.000000e+00+0.j, 0.000000e+00-0.j,
        0.000000e+00+0.j],
       [0.000000e+00+0.j, 6.123234e-17+0.j, 0.000000e+00+0.j,
        0.000000e+00-1.j],
       [0.000000e+00-0.j, 0.000000e+00+0.j, 1.000000e+00+0.j,
        0.000000e+00+0.j],
       [0.000000e+00+0.j, 0.000000e+00-1.j, 0.000000e+00+0.j,
        6.123234e-17+0.j]])

In [132]:
al='x';j=1;k=2;d=2; th=pi; c=1; t=0; crx = ctrl_R(al,j,k,d,th,c,t); Mnp = matrix2numpy(crx, dtype=complex); Mnp # sympy

array([[1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.-1.j],
       [0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j],
       [0.+0.j, 0.-1.j, 0.+0.j, 0.+0.j]])

In [138]:
j=1; k=2; d=2; N=3; th=math.pi; t=2; c=1; CRxnp = ctrl_Rx_qudits(d,N,t,c,j,k,th) # numpy # ok!
th=pi; crx = CRx_qudits_sympy(d,N,t,c,j,k,th); CRxsp = matrix2numpy(crx, dtype=complex) # sympy
print(np.linalg.norm(CRznp-CRzsp))

1.7319121124709866e-16


### Elementos não nulos de $C_{R_y^{jk}(\theta)}^{c\rightarrow t}$

Depois de algumas contas, notamos o seguinte. Se 
$$c<t$$
os elementos não nulos da rotação controlada são
\begin{align}
& \langle\cdots,k_{c-1},k_c,k_{c+1},\cdots,k_{t-1},j,k_{t+1},\cdots|C_{R_y^{jk}(\theta)}^{c\rightarrow t}|\cdots,k_{c-1},k_c,k_{c+1},\cdots,k_{t-1},j,k_{t+1},\cdots\rangle=\cos(k_c \theta/2), \\
& \langle\cdots,k_{c-1},k_c,k_{c+1},\cdots,k_{t-1},k,k_{t+1},\cdots|C_{R_y^{jk}(\theta)}^{c\rightarrow t}|\cdots,k_{c-1},k_c,k_{c+1},\cdots,k_{t-1},k,k_{t+1},\cdots\rangle=\cos(k_c \theta/2), \\
& \langle\cdots,k_{c-1},k_c,k_{c+1},\cdots,k_{t-1},j,k_{t+1},\cdots|C_{R_y^{jk}(\theta)}^{c\rightarrow t}|\cdots,k_{c-1},k_c,k_{c+1},\cdots,k_{t-1},k,k_{t+1},\cdots\rangle = -\sin(k_c \theta/2), \\
& \langle\cdots,k_{c-1},k_c,k_{c+1},\cdots,k_{t-1},k,k_{t+1},\cdots|C_{R_y^{jk}(\theta)}^{c\rightarrow t}|\cdots,k_{c-1},k_c,k_{c+1},\cdots,k_{t-1},j,k_{t+1},\cdots\rangle = -\sin(k_c \theta/2), \\
& \langle\cdots,k_{c-1},k_c,k_{c+1},\cdots,k_{t-1},l,k_{t+1},\cdots|C_{R_y^{jk}(\theta)}^{c\rightarrow t}|\cdots,k_{c-1},k_c,k_{c+1},\cdots,k_{t-1},l,k_{t+1},\cdots\rangle = 1, \\
\end{align}
pra $l\ne j;\ l\ne k;\ k_s = 1,\cdots,d;\ s=1,\cdots,N.$ Se 
$$c>t$$
os elementos não nulos da rotação controlada são
\begin{align}
& \langle\cdots,k_{t-1},j,k_{t+1},\cdots,k_{c-1},k_c,k_{c+1},\cdots|C_{R_y^{jk}(\theta)}^{c\rightarrow t}|\cdots,k_{t-1},j,k_{t+1},\cdots,k_{c-1},k_c,k_{c+1},\cdots\rangle=\cos(k_c \theta/2), \\
& \langle\cdots,k_{t-1},k,k_{t+1},\cdots,k_{c-1},k_c,k_{c+1},\cdots|C_{R_y^{jk}(\theta)}^{c\rightarrow t}|\cdots,k_{t-1},k,k_{t+1},\cdots,k_{c-1},k_c,k_{c+1},\cdots\rangle=\cos(k_c \theta/2), \\
& \langle\cdots,k_{t-1},j,k_{t+1},\cdots,k_{c-1},k_c,k_{c+1},\cdots|C_{R_y^{jk}(\theta)}^{c\rightarrow t}|\cdots,k_{t-1},k,k_{t+1},\cdots,k_{c-1},k_c,k_{c+1},\cdots\rangle = -\sin(k_c \theta/2), \\
& \langle\cdots,k_{t-1},k,k_{t+1},\cdots,k_{c-1},k_c,k_{c+1},\cdots|C_{R_y^{jk}(\theta)}^{c\rightarrow t}|\cdots,k_{t-1},j,k_{t+1},\cdots,k_{c-1},k_c,k_{c+1},\cdots\rangle = -\sin(k_c \theta/2), \\
& \langle\cdots,k_{t-1},l,k_{t+1},\cdots,k_{c-1},k_c,k_{c+1},\cdots|C_{R_y^{jk}(\theta)}^{c\rightarrow t}|\cdots,k_{t-1},l,k_{t+1},\cdots,k_{c-1},k_c,k_{c+1},\cdots\rangle = 1,
\end{align}
pra $l\ne j;\ l\ne k;\ k_s = 1,\cdots,d;\ s=1,\cdots,N.$

No final, os dois casos puderam ser implementados diretamente usando uma única função, sem necessidade de usar condicionais.

In [144]:
# Numpy

def ctrl_Ry_qudits(d,N,t,c,j,k,th): # return the controlled-rotation gate
    # d = qudit dimension; N = No. of qudits; t = target qudit (0,...,N-1); c = control qudit (0,...,N-1)
    # j,k are the Gell-Mann matrix indeces; th is the rotation angle
    D = d**N
    CR = np.zeros((D,D), dtype=complex) # set all d^2N elements to 0
    Dl = D//d # dimension for N-1 qudits
    for m in range (0,Dl): # run over all states of N-1 qdits
        local = dec2den(m,N-1,d) # values for the local basis of N-1 qudits
        if N == 2: # to avoid issues in this case
            angle = (local[0]*th)/2
        else:
            angle = (local[c]*th)/2
        listj = local.copy(); listj.insert(t,j-1); intj = den2dec(listj,d) # integer for the j state
        listk = local.copy(); listk.insert(t,k-1); intk = den2dec(listk,d) # integer for the k state
        CR[intj,intj] = math.cos(angle); CR[intk,intk] = CR[intj,intj]
        CR[intj,intk] = -math.sin(angle); CR[intk,intj] = -CR[intj,intk]
        for l in range(0,d):
            if l != j-1 and l != k-1:
                listl = local.copy(); listl.insert(t,l); intl = den2dec(listl,d) # integer for the l state
                CR[intl,intl] = 1
    return CR   

In [145]:
# Sympy

# general controlled rotation in sympy
def CRy_qudits_sympy(d,N,t,c,j,k,th):
    D = d**N
    CR = zeros(D,D)#; print(CR)
    Id = eye(d)#; print(Id)
    for m in range(0,d):
        ke = ket(d,m)#; print(ke)
        proj_m = ke*ke.T
        if c == 0:
            CRl = proj_m
        elif t == 0:
            CRl = f_Ry(j,k,d,m*th)
        else:
            CRl = Id
        for s in range(1,N):
            if s == c:
                CRl = tp(CRl,proj_m)
            elif s == t:
                CRl = tp(CRl,f_Ry(j,k,d,m*th))
            else:
                CRl = tp(CRl,Id)
        CR = CR + CRl
    return CR

In [146]:
j=1; k=2; d=2; N=2; th=pi; c=0; t=1; cry = CRy_qudits_sympy(d,N,t,c,j,k,th); CRsp = matrix2numpy(cry, dtype=complex); print(CRsp) # sympy

[[ 1.+0.j  0.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j  1.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j  0.+0.j -1.+0.j]
 [ 0.+0.j  0.+0.j  1.+0.j  0.+0.j]]


In [147]:
j=1; k=2; d=2; N=2; th=math.pi; c=0; t=1; CRnp = ctrl_Ry_qudits(d,N,t,c,j,k,th); print(CRnp) # numpy # not ok

[[ 1.000000e+00+0.j -0.000000e+00+0.j  0.000000e+00+0.j  0.000000e+00+0.j]
 [ 0.000000e+00-0.j  1.000000e+00+0.j  0.000000e+00+0.j  0.000000e+00+0.j]
 [ 0.000000e+00+0.j  0.000000e+00+0.j  6.123234e-17+0.j -1.000000e+00+0.j]
 [ 0.000000e+00+0.j  0.000000e+00+0.j  1.000000e+00-0.j  6.123234e-17+0.j]]


In [148]:
print(np.linalg.norm(CRsp-CRnp))

8.659560562354933e-17


In [150]:
j=1; k=2; d=2; N=3; th=pi; c=0; t=2; cry = CRy_qudits_sympy(d,N,t,c,j,k,th); CRsp = matrix2numpy(cry, dtype=complex) # sympy
th=math.pi; CRnp = ctrl_Ry_qudits(d,N,t,c,j,k,th) # numpy # not ok
print(np.linalg.norm(CRsp-CRnp))

1.2246467991473532e-16


In [151]:
j=1; k=2; d=2; N=4; th=pi; c=0; t=1; cry = CRy_qudits_sympy(d,N,t,c,j,k,th); CRsp = matrix2numpy(cry, dtype=complex) # sympy
th=math.pi; CRnp = ctrl_Ry_qudits(d,N,t,c,j,k,th) # numpy # not ok
print(np.linalg.norm(CRsp-CRnp))

1.7319121124709866e-16


Já os elementos não nulos de $C_{R_z^j(\theta)}^{c\rightarrow t}$ são
\begin{align}
& \langle\cdots,k_{c-1},k_c,k_{c+1},\cdots,k_{t-1},k,k_{t+1},\cdots|C_{R_z^{j}(\theta)}^{c\rightarrow t}|\cdots,k_{c-1},k_c,k_{c+1},\cdots,k_{t-1},k,k_{t+1},\cdots\rangle =  \exp\Big(-i\frac{k_c \theta}{2}\sqrt{\frac{2}{j(j+1)}}\Big);\ k=1,\cdots,j, \\
& \langle\cdots,k_{c-1},k_c,k_{c+1},\cdots,k_{t-1},k,k_{t+1},\cdots|C_{R_z^{j}(\theta)}^{c\rightarrow t}|\cdots,k_{c-1},k_c,k_{c+1},\cdots,k_{t-1},k,k_{t+1},\cdots\rangle =  \exp\Big(i\frac{jk_c \theta}{2}\sqrt{\frac{2}{j(j+1)}}\Big);\ k=j+1, \\
& \langle\cdots,k_{c-1},k_c,k_{c+1},\cdots,k_{t-1},k,k_{t+1},\cdots|C_{R_z^{j}(\theta)}^{c\rightarrow t}|\cdots,k_{c-1},k_c,k_{c+1},\cdots,k_{t-1},k,k_{t+1},\cdots\rangle =  1;\ k=j,\cdots,d.
\end{align}

In [108]:
# Numpy

def ctrl_Rz_qudits(d,N,t,c,j,th): # return the controlled-rotation gate
    # d = qudit dimension; N = No. of qudits; t = target qudit (0,...,N-1); c = control qudit (0,...,N-1)
    # j,k are the Gell-Mann matrix indeces; th is the rotation angle
    D = d**N
    CR = np.zeros((D,D), dtype=complex) # set all d^2N elements to 0
    Dl = D//d # dimension for N-1 qudits
    for m in range (0,Dl): # run over all states of N-1 qdits
        local = dec2den(m,N-1,d) # values for the local basis of N-1 qudits
        if N == 2: # to avoid problems when N=2
            loc = local[0]
        else:
            loc = local[c]
        angle = ((loc*th)/2)*sqrt(2/(j*(j+1)))
        for k in range(0,d):
            listk = local.copy(); listk.insert(t,k) # insert k in position t of the list
            intk = den2dec(listk,d) # integer for the k state
            if k < j:
                CR[intk,intk] = math.cos(angle) - 1j*math.sin(angle)
            elif k == j:
                angle = j*angle
                CR[intk,intk] = math.cos(angle) + 1j*math.sin(angle)
            elif k > j:
                CR[intk,intk] = 1
    return CR   

Para a implementação em Sympy:
$$C_{R_z^{jk}(\theta)}^{c\rightarrow t} = I_{\overline{c}}\otimes I_{\overline{t}}\otimes\sum_{l=0}^{d-1}|l\rangle\langle l|_c \otimes R_z^{jk}(l\theta)_t.$$

In [109]:
# Sympy

# general controlled rotation in sympy
def CRz_qudits_sympy(d,N,t,c,j,k,th):
    D = d**N
    CR = zeros(D,D)
    Id = eye(d)
    for m in range(0,d):
        ke = ket(d,m)
        s = 0
        if s == c:
            CRl = ke*ke.T
        elif s == t:
            CRl = f_Rz(j,d,m*th)
        else:
            CRl = Id
        for s in range(1,N):
            if s == c:
                CRl = tp(CRl,(ke*ke.T))
            elif s == t:
                CRl = tp(CRl,f_Rz(j,d,m*th))
            else:
                CRl = tp(CRl,Id)
        CR = CR + CRl
    return CR

In [110]:
j=1; d=2; N=2; th=math.pi; c=0; t=1; CRznp = ctrl_Rz_qudits(d,N,t,c,j,th); print(CRznp) # numpy # ok!

[[1.000000e+00+0.j 0.000000e+00+0.j 0.000000e+00+0.j 0.000000e+00+0.j]
 [0.000000e+00+0.j 1.000000e+00+0.j 0.000000e+00+0.j 0.000000e+00+0.j]
 [0.000000e+00+0.j 0.000000e+00+0.j 6.123234e-17-1.j 0.000000e+00+0.j]
 [0.000000e+00+0.j 0.000000e+00+0.j 0.000000e+00+0.j 6.123234e-17+1.j]]


In [111]:
j=1; d=2; N=2; th=pi; c=0; t=1; crz = CRz_qudits_sympy(d,N,t,c,j,k,th); CRzsp = matrix2numpy(crz, dtype=complex); print(CRzsp) # sympy

[[1.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 1.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.-1.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+1.j]]


In [112]:
j=1; d=2; N=2; th=math.pi; c=1; t=0; CRznp = ctrl_Rz_qudits(d,N,t,c,j,th); print(CRznp) # numpy # ok!

[[1.000000e+00+0.j 0.000000e+00+0.j 0.000000e+00+0.j 0.000000e+00+0.j]
 [0.000000e+00+0.j 6.123234e-17-1.j 0.000000e+00+0.j 0.000000e+00+0.j]
 [0.000000e+00+0.j 0.000000e+00+0.j 1.000000e+00+0.j 0.000000e+00+0.j]
 [0.000000e+00+0.j 0.000000e+00+0.j 0.000000e+00+0.j 6.123234e-17+1.j]]


In [113]:
j=1; d=2; N=2; th=pi; c=1; t=0; crz = CRz_qudits_sympy(d,N,t,c,j,k,th); CRzsp = matrix2numpy(crz, dtype=complex); print(CRzsp) # sympy

[[1.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.-1.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 1.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+1.j]]


In [117]:
# use this kind of code to do more tests
j=1; d=2; N=3; th=math.pi; c=0; t=2; CRznp = ctrl_Rz_qudits(d,N,t,c,j,th) # numpy # ok!
th=pi; crz = CRz_qudits_sympy(d,N,t,c,j,k,th); CRzsp = matrix2numpy(crz, dtype=complex) # sympy
print(np.linalg.norm(CRznp-CRzsp))

1.2246467991473532e-16


In [118]:
j=1; d=2; N=3; th=math.pi; c=0; t=1; CRznp = ctrl_Rz_qudits(d,N,t,c,j,th) # numpy # ok!
th=pi; crz = CRz_qudits_sympy(d,N,t,c,j,k,th); CRzsp = matrix2numpy(crz, dtype=complex) # sympy
print(np.linalg.norm(CRznp-CRzsp))

1.2246467991473532e-16


In [119]:
j=1; d=2; N=4; th=math.pi; c=0; t=1; CRznp = ctrl_Rz_qudits(d,N,t,c,j,th) # numpy # ok!
th=pi; crz = CRz_qudits_sympy(d,N,t,c,j,k,th); CRzsp = matrix2numpy(crz, dtype=complex) # sympy
print(np.linalg.norm(CRznp-CRzsp))

1.7319121124709866e-16
